# Info
name = "Test Post on the 2nd Jan"
date = "2019-01-02T07:32:00Z"
description = "A cool description of a post"

# Content
content = """

This is some content for the blog post. It is longer and support markdown. Woop woop.

"""
