# Info
title = "Weekend in Germany, May 4th-5th 2019"
date = "2019-05-11T23:20:34+0200"
description = "Some photos from a weekend away in Halle and Leipzig, Germany"

# Content
content = """

Some photos from a short weekend trip from Berlin to Halle and Leipzig. Being a bit of an architecture nerd, there are definitely too many photos of buildings still on the camera.

This was my first time getting out of Berlin and seeing a bit more of *actual Germany.* Seeing as Berlin has a reputation for being a bit unique.

All of these are raw and unedited. Also my photography leaves a lot to be desired still.

![Street and restaurant](https://imgur.com/kk8ikMn.jpg)
This was the street that we stayed on.

![Stop wars](https://imgur.com/PXBmfOx.jpg)

![Boat on the river](https://imgur.com/g5bP14Q.jpg)

![Bridge across the river](https://imgur.com/EwVY3RK.jpg)

![Old red building](https://imgur.com/isCMStm.jpg)

![Johannes and Johanna](https://imgur.com/a4qCe5Q.jpg)
Johannes and Johanna

![Stalin at Post-War Museum](https://imgur.com/2FXOQai.jpg)
A visit to the Leipzig Post-War Museum

![Torn GDR flag](https://imgur.com/jhdwCXv.jpg)
A torn German Democratic Republic flag

![German Eagle statue](https://imgur.com/DQJKQhS.jpg)
A statue which once bore the Nazi swastika, chiseled off since being captured

![Stalinist sculpture](https://imgur.com/1BENnjy.jpg)

![Bookbag](https://imgur.com/FOxArod.jpg)
During the GDR, students were taken to visit military checkpoints, where members of the Stasi would attempt to recruit them as spies

![Documentary](https://imgur.com/qGn4eEL.jpg)

![Eiffel Tower with motorbike](https://imgur.com/GyrB3zI.jpg)

![Justice building](https://imgur.com/FQm9rGD.jpg)
Some incredible, detailed architecture, one of many old buildings throughout Leipzig

![Clara-Zetkin Park](https://imgur.com/qUJGl18.jpg)
Clara-Zetkin Park

![Johannes and Tom](https://imgur.com/BcwMMHa.jpg)

![Johannes and Tom 2](https://imgur.com/G3fofrd.jpg)

![Women's run](https://imgur.com/M2LLYoZ.jpg)
We were walking through just as they started a women's run

![Spire at end of street](https://imgur.com/i6oHsJ3.jpg)

![Graffiti](https://imgur.com/Z6MLdW5.jpg)

![Tattoo](https://imgur.com/RPjVtvc.jpg)

![Johannes](https://imgur.com/xx1vgdO.jpg)

![Building](https://imgur.com/4Z9V7MN.jpg)
A gothic masterpiece

![Train](https://imgur.com/MbRsA9l.jpg)
Heading back to Halle by train, almost certainly on the wrong ticket

This trip was an enormous amount of fun. I look forward to visiting more places across Germany in the future.

"""
